name: "Build and Pack FrapaClonia"
description: "Build and pack FrapaClonia for multiple platforms"

inputs:
  version:
    description: "Version tag for the output files"
    required: true
    default: "0.0.1"

  rids:
    description: "Space-separated list of RuntimeIdentifiers to build on this runner"
    required: true

  configuration:
    description: "Build configuration"
    required: false
    default: "Release"

  publish_aot:
    description: "Enable NativeAOT"
    required: false
    default: "true"

  self_contained:
    description: "Publish self-contained"
    required: false
    default: "true"

  pack_macos_zip:
    description: "Whether to create macOS zip archives (normally false when packaging DMG directly)"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: "10.0.x"

    - name: Install Linux toolchains (for AOT/cross-arch)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        set -euo pipefail
        sudo apt-get update
        # Tooling commonly needed by NativeAOT and cross-arch Linux targets.
        sudo apt-get install -y --no-install-recommends \
          clang lld zlib1g-dev \
          musl-tools \
          gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu libc6-dev-arm64-cross

    - name: Configure objcopy for cross-arch NativeAOT
      if: runner.os == 'Linux'
      shell: bash
      run: |
        set -euo pipefail

        mkdir -p .ci-bin

        cat > .ci-bin/objcopy <<'SH'
        #!/usr/bin/env bash
        set -euo pipefail

        # NativeAOT uses `objcopy` to split debug symbols. When cross-building ARM64 on x64,
        # using aarch64 objcopy is more reliable.
        infile=""
        # Try to find the input file by walking args from the end and picking the first
        # existing regular file. This works for common forms like:
        #   objcopy --strip-debug --strip-unneeded <infile>
        #   objcopy --only-keep-debug <infile> <outfile>
        for ((i=$#; i>=1; i--)); do
          candidate="${!i}"
          if [[ -n "${candidate:-}" && "${candidate}" != -* && -f "${candidate}" ]]; then
            infile="${candidate}"
            break
          fi
        done

        if [[ -n "${infile:-}" ]] && command -v file >/dev/null 2>&1; then
          if file "$infile" 2>/dev/null | grep -Eqi "aarch64|ARM aarch64"; then
            if command -v aarch64-linux-gnu-objcopy >/dev/null 2>&1; then
              exec aarch64-linux-gnu-objcopy "$@"
            fi
          fi
        fi

        exec /usr/bin/objcopy "$@"
        SH

        chmod +x .ci-bin/objcopy
        echo "$GITHUB_WORKSPACE/.ci-bin" >> "$GITHUB_PATH"

    - name: Restore dependencies
      shell: bash
      run: dotnet restore

    - name: Publish (macOS/Linux)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        set -euo pipefail
        CONFIG='${{ inputs.configuration }}'
        VERSION='${{ inputs.version }}'
        AOT='${{ inputs.publish_aot }}'
        SELF='${{ inputs.self_contained }}'
        for RID in ${{ inputs.rids }}; do
          echo "Publishing $RID (AOT=$AOT, self-contained=$SELF)"
          dotnet publish src/FrapaClonia/FrapaClonia.csproj \
            -c "$CONFIG" \
            -r "$RID" \
            -p:PublishAot=$AOT \
            -p:Version=$VERSION \
            --self-contained $SELF \
            -o "out/$RID"

          # Remove debug symbols from shipped artifacts.
          find "out/$RID" -name '*.pdb' -type f -delete || true
          find "out/$RID" -name '*.dSYM' -type d -prune -exec rm -rf {} + || true
        done

    - name: Publish (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $Config = '${{ inputs.configuration }}'
        $Version = '${{ inputs.version }}'
        $Aot = '${{ inputs.publish_aot }}'
        $Self = '${{ inputs.self_contained }}'
        foreach ($Rid in '${{ inputs.rids }}'.Split(' ', [System.StringSplitOptions]::RemoveEmptyEntries)) {
          Write-Host "Publishing $Rid (AOT=$Aot, self-contained=$Self)"
          dotnet publish src/FrapaClonia/FrapaClonia.csproj `
            -c $Config `
            -r $Rid `
            -p:PublishAot=$Aot `
            -p:Version=$Version `
            --self-contained $Self `
            -o ("out/" + $Rid)

          # Remove debug symbols from shipped artifacts.
          Get-ChildItem -Path ("out/" + $Rid) -Recurse -Force -ErrorAction SilentlyContinue |
            Where-Object { $_.Name -like '*.pdb' } |
            Remove-Item -Force -ErrorAction SilentlyContinue

          Get-ChildItem -Path ("out/" + $Rid) -Recurse -Force -ErrorAction SilentlyContinue |
            Where-Object { $_.PSIsContainer -and $_.Name -like '*.dSYM' } |
            Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
        }

    - name: Pack (macOS ZIP)
      if: runner.os == 'macOS' && inputs.pack_macos_zip == 'true'
      shell: bash
      run: |
        set -euo pipefail
        VERSION='${{ inputs.version }}'
        for RID in ${{ inputs.rids }}; do
          cd "out/$RID"
          zip -r "../../FrapaClonia-${VERSION}-${RID}.zip" .
          cd ../..
        done

    - name: Pack (Windows ZIP)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $Version = '${{ inputs.version }}'
        foreach ($Rid in '${{ inputs.rids }}'.Split(' ', [System.StringSplitOptions]::RemoveEmptyEntries)) {
          $Zip = "FrapaClonia-$Version-$Rid.zip"
          if (Test-Path $Zip) { Remove-Item $Zip -Force }
          Compress-Archive -Path ("out/" + $Rid + "/*") -DestinationPath $Zip
        }

    - name: Pack (Linux tar.gz)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        set -euo pipefail
        VERSION='${{ inputs.version }}'
        for RID in ${{ inputs.rids }}; do
          cd "out/$RID"
          tar -czf "../../FrapaClonia-${VERSION}-${RID}.tar.gz" .
          cd ../..
        done
