//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrapaClonia.Infrastructure.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FrapaClonia.Infrastructure.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        internal static string ActiveProxies {
            get {
                return ResourceManager.GetString("ActiveProxies", resourceCulture);
            }
        }
        
        internal static string AddProxy {
            get {
                return ResourceManager.GetString("AddProxy", resourceCulture);
            }
        }
        
        internal static string AddVisitor {
            get {
                return ResourceManager.GetString("AddVisitor", resourceCulture);
            }
        }
        
        internal static string AllLevels {
            get {
                return ResourceManager.GetString("AllLevels", resourceCulture);
            }
        }
        
        internal static string AllTypes {
            get {
                return ResourceManager.GetString("AllTypes", resourceCulture);
            }
        }
        
        internal static string AllowedUsers {
            get {
                return ResourceManager.GetString("AllowedUsers", resourceCulture);
            }
        }
        
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        internal static string ApplicationMode {
            get {
                return ResourceManager.GetString("ApplicationMode", resourceCulture);
            }
        }
        
        internal static string Architecture {
            get {
                return ResourceManager.GetString("Architecture", resourceCulture);
            }
        }
        
        internal static string Audience {
            get {
                return ResourceManager.GetString("Audience", resourceCulture);
            }
        }
        
        internal static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        internal static string AutoDetect {
            get {
                return ResourceManager.GetString("AutoDetect", resourceCulture);
            }
        }
        
        internal static string AutoDetectFrpcToolTip {
            get {
                return ResourceManager.GetString("AutoDetectFrpcToolTip", resourceCulture);
            }
        }
        
        internal static string AutoScroll {
            get {
                return ResourceManager.GetString("AutoScroll", resourceCulture);
            }
        }
        
        internal static string AutoStart {
            get {
                return ResourceManager.GetString("AutoStart", resourceCulture);
            }
        }
        
        internal static string AutomaticallyLaunchFrapaClonia {
            get {
                return ResourceManager.GetString("AutomaticallyLaunchFrapaClonia", resourceCulture);
            }
        }
        
        internal static string BandwidthLimit {
            get {
                return ResourceManager.GetString("BandwidthLimit", resourceCulture);
            }
        }
        
        internal static string BasicSettings {
            get {
                return ResourceManager.GetString("BasicSettings", resourceCulture);
            }
        }
        
        internal static string BinaryPath {
            get {
                return ResourceManager.GetString("BinaryPath", resourceCulture);
            }
        }
        
        internal static string BindAddr {
            get {
                return ResourceManager.GetString("BindAddr", resourceCulture);
            }
        }
        
        internal static string BindIPPortInfo {
            get {
                return ResourceManager.GetString("BindIPPortInfo", resourceCulture);
            }
        }
        
        internal static string BindPort {
            get {
                return ResourceManager.GetString("BindPort", resourceCulture);
            }
        }
        
        internal static string BindSettings {
            get {
                return ResourceManager.GetString("BindSettings", resourceCulture);
            }
        }
        
        internal static string BothMethodsUse {
            get {
                return ResourceManager.GetString("BothMethodsUse", resourceCulture);
            }
        }
        
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        internal static string BrowseToolTip {
            get {
                return ResourceManager.GetString("BrowseToolTip", resourceCulture);
            }
        }
        
        internal static string BuildInfo {
            get {
                return ResourceManager.GetString("BuildInfo", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string ChangesWillTakeEffectImmediately {
            get {
                return ResourceManager.GetString("ChangesWillTakeEffectImmediately", resourceCulture);
            }
        }
        
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        internal static string CheckDeployment {
            get {
                return ResourceManager.GetString("CheckDeployment", resourceCulture);
            }
        }
        
        internal static string CheckDocker {
            get {
                return ResourceManager.GetString("CheckDocker", resourceCulture);
            }
        }
        
        internal static string CheckFrpcPathToolTip {
            get {
                return ResourceManager.GetString("CheckFrpcPathToolTip", resourceCulture);
            }
        }
        
        internal static string CheckVersions {
            get {
                return ResourceManager.GetString("CheckVersions", resourceCulture);
            }
        }
        
        internal static string CheckingFrpc {
            get {
                return ResourceManager.GetString("CheckingFrpc", resourceCulture);
            }
        }
        
        internal static string ChooseHowYouWantToDeployAndRunFrpc {
            get {
                return ResourceManager.GetString("ChooseHowYouWantToDeployAndRunFrpc", resourceCulture);
            }
        }
        
        internal static string ChooseYourPreferredColorTheme {
            get {
                return ResourceManager.GetString("ChooseYourPreferredColorTheme", resourceCulture);
            }
        }
        
        internal static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        internal static string ClearAllLogs {
            get {
                return ResourceManager.GetString("ClearAllLogs", resourceCulture);
            }
        }
        
        internal static string ClientSecret {
            get {
                return ResourceManager.GetString("ClientSecret", resourceCulture);
            }
        }
        
        internal static string CommaSeparatedList {
            get {
                return ResourceManager.GetString("CommaSeparatedList", resourceCulture);
            }
        }
        
        internal static string CommaSeparatedListOfAllowedUsers {
            get {
                return ResourceManager.GetString("CommaSeparatedListOfAllowedUsers", resourceCulture);
            }
        }
        
        internal static string CompressDataToReduceBandwidthUsage {
            get {
                return ResourceManager.GetString("CompressDataToReduceBandwidthUsage", resourceCulture);
            }
        }
        
        internal static string ConfigPresets {
            get {
                return ResourceManager.GetString("ConfigPresets", resourceCulture);
            }
        }
        
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        internal static string ConfigurationError {
            get {
                return ResourceManager.GetString("ConfigurationError", resourceCulture);
            }
        }
        
        internal static string ConfigurationIsValid {
            get {
                return ResourceManager.GetString("ConfigurationIsValid", resourceCulture);
            }
        }
        
        internal static string ConfigurationLocation {
            get {
                return ResourceManager.GetString("ConfigurationLocation", resourceCulture);
            }
        }
        
        internal static string ConfigurationStoredInAppDir {
            get {
                return ResourceManager.GetString("ConfigurationStoredInAppDir", resourceCulture);
            }
        }
        
        internal static string Configure {
            get {
                return ResourceManager.GetString("Configure", resourceCulture);
            }
        }
        
        internal static string ConfigureAVisitorToConnect {
            get {
                return ResourceManager.GetString("ConfigureAVisitorToConnect", resourceCulture);
            }
        }
        
        internal static string ConfigureAndManageSecureTunnelVisitors {
            get {
                return ResourceManager.GetString("ConfigureAndManageSecureTunnelVisitors", resourceCulture);
            }
        }
        
        internal static string ConfigureAndManageYourFrpcProxyConfigurations {
            get {
                return ResourceManager.GetString("ConfigureAndManageYourFrpcProxyConfigurations", resourceCulture);
            }
        }
        
        internal static string ConfigureFrpcToolTip {
            get {
                return ResourceManager.GetString("ConfigureFrpcToolTip", resourceCulture);
            }
        }
        
        internal static string ConfigureYourProxySettingsBelow {
            get {
                return ResourceManager.GetString("ConfigureYourProxySettingsBelow", resourceCulture);
            }
        }
        
        internal static string ConnectionSettings {
            get {
                return ResourceManager.GetString("ConnectionSettings", resourceCulture);
            }
        }
        
        internal static string ContainerName {
            get {
                return ResourceManager.GetString("ContainerName", resourceCulture);
            }
        }
        
        internal static string CreateProxy {
            get {
                return ResourceManager.GetString("CreateProxy", resourceCulture);
            }
        }
        
        internal static string CreateYourFirstProxyConfiguration {
            get {
                return ResourceManager.GetString("CreateYourFirstProxyConfiguration", resourceCulture);
            }
        }
        
        internal static string CreateYourFirstVisitor {
            get {
                return ResourceManager.GetString("CreateYourFirstVisitor", resourceCulture);
            }
        }
        
        internal static string CrossPlatformFrpcVisualClient {
            get {
                return ResourceManager.GetString("CrossPlatformFrpcVisualClient", resourceCulture);
            }
        }
        
        internal static string CustomDomains {
            get {
                return ResourceManager.GetString("CustomDomains", resourceCulture);
            }
        }
        
        internal static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        internal static string DefaultPort {
            get {
                return ResourceManager.GetString("DefaultPort", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string DeletePreset {
            get {
                return ResourceManager.GetString("DeletePreset", resourceCulture);
            }
        }
        
        internal static string DeleteProxy {
            get {
                return ResourceManager.GetString("DeleteProxy", resourceCulture);
            }
        }
        
        internal static string DeleteProxyToolTip {
            get {
                return ResourceManager.GetString("DeleteProxyToolTip", resourceCulture);
            }
        }
        
        internal static string DeleteVisitor {
            get {
                return ResourceManager.GetString("DeleteVisitor", resourceCulture);
            }
        }
        
        internal static string DetectedFrpcInstallations {
            get {
                return ResourceManager.GetString("DetectedFrpcInstallations", resourceCulture);
            }
        }
        
        internal static string DeployNative {
            get {
                return ResourceManager.GetString("DeployNative", resourceCulture);
            }
        }
        
        internal static string Deployment {
            get {
                return ResourceManager.GetString("Deployment", resourceCulture);
            }
        }
        
        internal static string DeploymentInformation {
            get {
                return ResourceManager.GetString("DeploymentInformation", resourceCulture);
            }
        }
        
        internal static string DeploymentMode {
            get {
                return ResourceManager.GetString("DeploymentMode", resourceCulture);
            }
        }
        
        internal static string DeploymentStatus {
            get {
                return ResourceManager.GetString("DeploymentStatus", resourceCulture);
            }
        }
        
        internal static string DetectingFrpc {
            get {
                return ResourceManager.GetString("DetectingFrpc", resourceCulture);
            }
        }
        
        internal static string DialTimeout {
            get {
                return ResourceManager.GetString("DialTimeout", resourceCulture);
            }
        }
        
        internal static string DockerComposePath {
            get {
                return ResourceManager.GetString("DockerComposePath", resourceCulture);
            }
        }
        
        internal static string DockerDeployment {
            get {
                return ResourceManager.GetString("DockerDeployment", resourceCulture);
            }
        }
        
        internal static string DockerDeploymentRequiresDocker {
            get {
                return ResourceManager.GetString("DockerDeploymentRequiresDocker", resourceCulture);
            }
        }
        
        internal static string DockerImage {
            get {
                return ResourceManager.GetString("DockerImage", resourceCulture);
            }
        }
        
        internal static string DockerStatus {
            get {
                return ResourceManager.GetString("DockerStatus", resourceCulture);
            }
        }
        
        internal static string DomainSettings {
            get {
                return ResourceManager.GetString("DomainSettings", resourceCulture);
            }
        }
        
        internal static string DownloadAndDeploy {
            get {
                return ResourceManager.GetString("DownloadAndDeploy", resourceCulture);
            }
        }
        
        internal static string DownloadDirect {
            get {
                return ResourceManager.GetString("DownloadDirect", resourceCulture);
            }
        }
        
        internal static string DownloadDirectToolTip {
            get {
                return ResourceManager.GetString("DownloadDirectToolTip", resourceCulture);
            }
        }
        
        internal static string DownloadFromGitHub {
            get {
                return ResourceManager.GetString("DownloadFromGitHub", resourceCulture);
            }
        }
        
        internal static string DownloadFromWeb {
            get {
                return ResourceManager.GetString("DownloadFromWeb", resourceCulture);
            }
        }
        
        internal static string DownloadFromWebDescription {
            get {
                return ResourceManager.GetString("DownloadFromWebDescription", resourceCulture);
            }
        }
        
        internal static string DownloadFrpc {
            get {
                return ResourceManager.GetString("DownloadFrpc", resourceCulture);
            }
        }
        
        internal static string DownloadFrpcFromGitHub {
            get {
                return ResourceManager.GetString("DownloadFrpcFromGitHub", resourceCulture);
            }
        }
        
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        internal static string DuplicatePreset {
            get {
                return ResourceManager.GetString("DuplicatePreset", resourceCulture);
            }
        }
        
        internal static string DuplicateProxy {
            get {
                return ResourceManager.GetString("DuplicateProxy", resourceCulture);
            }
        }
        
        internal static string DuplicateProxyToolTip {
            get {
                return ResourceManager.GetString("DuplicateProxyToolTip", resourceCulture);
            }
        }
        
        internal static string EG_1MB_256KB {
            get {
                return ResourceManager.GetString("EG_1MB_256KB", resourceCulture);
            }
        }
        
        internal static string EG_www_example_com {
            get {
                return ResourceManager.GetString("EG_www_example_com", resourceCulture);
            }
        }
        
        internal static string EditProxy {
            get {
                return ResourceManager.GetString("EditProxy", resourceCulture);
            }
        }
        
        internal static string EditProxyToolTip {
            get {
                return ResourceManager.GetString("EditProxyToolTip", resourceCulture);
            }
        }
        
        internal static string EditProxyWindowTitle {
            get {
                return ResourceManager.GetString("EditProxyWindowTitle", resourceCulture);
            }
        }
        
        internal static string EditVisitor {
            get {
                return ResourceManager.GetString("EditVisitor", resourceCulture);
            }
        }
        
        internal static string EditVisitorWindowTitle {
            get {
                return ResourceManager.GetString("EditVisitorWindowTitle", resourceCulture);
            }
        }
        
        internal static string EnableCompression {
            get {
                return ResourceManager.GetString("EnableCompression", resourceCulture);
            }
        }
        
        internal static string EnableEncryption {
            get {
                return ResourceManager.GetString("EnableEncryption", resourceCulture);
            }
        }
        
        internal static string EnableHealthCheck {
            get {
                return ResourceManager.GetString("EnableHealthCheck", resourceCulture);
            }
        }
        
        internal static string EnableTLS {
            get {
                return ResourceManager.GetString("EnableTLS", resourceCulture);
            }
        }
        
        internal static string EncryptCommunicationWithTheFrpsServer {
            get {
                return ResourceManager.GetString("EncryptCommunicationWithTheFrpsServer", resourceCulture);
            }
        }
        
        internal static string EncryptTheConnectionBetweenClientAndServer {
            get {
                return ResourceManager.GetString("EncryptTheConnectionBetweenClientAndServer", resourceCulture);
            }
        }
        
        internal static string EnterYourAuthenticationToken {
            get {
                return ResourceManager.GetString("EnterYourAuthenticationToken", resourceCulture);
            }
        }
        
        internal static string Entries {
            get {
                return ResourceManager.GetString("Entries", resourceCulture);
            }
        }
        
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        internal static string ExportAll {
            get {
                return ResourceManager.GetString("ExportAll", resourceCulture);
            }
        }
        
        internal static string ExportFailed {
            get {
                return ResourceManager.GetString("ExportFailed", resourceCulture);
            }
        }
        
        internal static string ExportLogsToFile {
            get {
                return ResourceManager.GetString("ExportLogsToFile", resourceCulture);
            }
        }
        
        internal static string ExportPreset {
            get {
                return ResourceManager.GetString("ExportPreset", resourceCulture);
            }
        }
        
        internal static string FrpcBinaryPath {
            get {
                return ResourceManager.GetString("FrpcBinaryPath", resourceCulture);
            }
        }
        
        internal static string FrpcConfiguration {
            get {
                return ResourceManager.GetString("FrpcConfiguration", resourceCulture);
            }
        }
        
        internal static string FrpcExecutableLocation {
            get {
                return ResourceManager.GetString("FrpcExecutableLocation", resourceCulture);
            }
        }
        
        internal static string FrpcExecutablePathDescription {
            get {
                return ResourceManager.GetString("FrpcExecutablePathDescription", resourceCulture);
            }
        }
        
        internal static string FrpcNotConfigured {
            get {
                return ResourceManager.GetString("FrpcNotConfigured", resourceCulture);
            }
        }
        
        internal static string FrpcNotFoundOrInvalid {
            get {
                return ResourceManager.GetString("FrpcNotFoundOrInvalid", resourceCulture);
            }
        }
        
        internal static string FrpcNotRunning {
            get {
                return ResourceManager.GetString("FrpcNotRunning", resourceCulture);
            }
        }
        
        internal static string FrpcRunning {
            get {
                return ResourceManager.GetString("FrpcRunning", resourceCulture);
            }
        }
        
        internal static string FrpcStatus {
            get {
                return ResourceManager.GetString("FrpcStatus", resourceCulture);
            }
        }
        
        internal static string FrpcVersion {
            get {
                return ResourceManager.GetString("FrpcVersion", resourceCulture);
            }
        }
        
        internal static string FrpcVersions {
            get {
                return ResourceManager.GetString("FrpcVersions", resourceCulture);
            }
        }
        
        internal static string GenerateDockerComposeYml {
            get {
                return ResourceManager.GetString("GenerateDockerComposeYml", resourceCulture);
            }
        }
        
        internal static string GetFrpc {
            get {
                return ResourceManager.GetString("GetFrpc", resourceCulture);
            }
        }
        
        internal static string GetFrpcDescription {
            get {
                return ResourceManager.GetString("GetFrpcDescription", resourceCulture);
            }
        }
        
        internal static string HTTPAuthentication {
            get {
                return ResourceManager.GetString("HTTPAuthentication", resourceCulture);
            }
        }
        
        internal static string HeaderNameValue {
            get {
                return ResourceManager.GetString("HeaderNameValue", resourceCulture);
            }
        }
        
        internal static string HeadersLabel {
            get {
                return ResourceManager.GetString("HeadersLabel", resourceCulture);
            }
        }
        
        internal static string HealthCheck {
            get {
                return ResourceManager.GetString("HealthCheck", resourceCulture);
            }
        }
        
        internal static string HeartbeatInterval {
            get {
                return ResourceManager.GetString("HeartbeatInterval", resourceCulture);
            }
        }
        
        internal static string HeartbeatTimeout {
            get {
                return ResourceManager.GetString("HeartbeatTimeout", resourceCulture);
            }
        }
        
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        internal static string ImportFailed {
            get {
                return ResourceManager.GetString("ImportFailed", resourceCulture);
            }
        }
        
        internal static string ImportPreset {
            get {
                return ResourceManager.GetString("ImportPreset", resourceCulture);
            }
        }
        
        internal static string InUse {
            get {
                return ResourceManager.GetString("InUse", resourceCulture);
            }
        }
        
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        internal static string InstallAsSystemService {
            get {
                return ResourceManager.GetString("InstallAsSystemService", resourceCulture);
            }
        }
        
        internal static string InstallCommand {
            get {
                return ResourceManager.GetString("InstallCommand", resourceCulture);
            }
        }
        
        internal static string InstallMethod {
            get {
                return ResourceManager.GetString("InstallMethod", resourceCulture);
            }
        }
        
        internal static string InstallService {
            get {
                return ResourceManager.GetString("InstallService", resourceCulture);
            }
        }
        
        internal static string InstallViaPackageManager {
            get {
                return ResourceManager.GetString("InstallViaPackageManager", resourceCulture);
            }
        }
        
        internal static string InterfaceLanguage {
            get {
                return ResourceManager.GetString("InterfaceLanguage", resourceCulture);
            }
        }
        
        internal static string IntervalSeconds {
            get {
                return ResourceManager.GetString("IntervalSeconds", resourceCulture);
            }
        }
        
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        internal static string LanguageAndRegion {
            get {
                return ResourceManager.GetString("LanguageAndRegion", resourceCulture);
            }
        }
        
        internal static string LeaveEmptyIfUsingCustomDomains {
            get {
                return ResourceManager.GetString("LeaveEmptyIfUsingCustomDomains", resourceCulture);
            }
        }
        
        internal static string LeaveEmptyToAllowAllUsers {
            get {
                return ResourceManager.GetString("LeaveEmptyToAllowAllUsers", resourceCulture);
            }
        }
        
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        internal static string LimitBandwidthForThisProxy {
            get {
                return ResourceManager.GetString("LimitBandwidthForThisProxy", resourceCulture);
            }
        }
        
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        internal static string LoadingVersions {
            get {
                return ResourceManager.GetString("LoadingVersions", resourceCulture);
            }
        }
        
        internal static string LoadingVisitors {
            get {
                return ResourceManager.GetString("LoadingVisitors", resourceCulture);
            }
        }
        
        internal static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        internal static string LocalAddress {
            get {
                return ResourceManager.GetString("LocalAddress", resourceCulture);
            }
        }
        
        internal static string LocalIP {
            get {
                return ResourceManager.GetString("LocalIP", resourceCulture);
            }
        }
        
        internal static string LocalPath {
            get {
                return ResourceManager.GetString("LocalPath", resourceCulture);
            }
        }
        
        internal static string LocalPort {
            get {
                return ResourceManager.GetString("LocalPort", resourceCulture);
            }
        }
        
        internal static string LocalPortToListenOn {
            get {
                return ResourceManager.GetString("LocalPortToListenOn", resourceCulture);
            }
        }
        
        internal static string LocalSettings {
            get {
                return ResourceManager.GetString("LocalSettings", resourceCulture);
            }
        }
        
        internal static string LogLevelLabel {
            get {
                return ResourceManager.GetString("LogLevelLabel", resourceCulture);
            }
        }
        
        internal static string LogTo {
            get {
                return ResourceManager.GetString("LogTo", resourceCulture);
            }
        }
        
        internal static string LoggingSection {
            get {
                return ResourceManager.GetString("LoggingSection", resourceCulture);
            }
        }
        
        internal static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        internal static string LogsWillAppearHere {
            get {
                return ResourceManager.GetString("LogsWillAppearHere", resourceCulture);
            }
        }
        
        internal static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        internal static string MaxDays {
            get {
                return ResourceManager.GetString("MaxDays", resourceCulture);
            }
        }
        
        internal static string MaxFailed {
            get {
                return ResourceManager.GetString("MaxFailed", resourceCulture);
            }
        }
        
        internal static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        internal static string MonitorTheHealthOfTheLocalService {
            get {
                return ResourceManager.GetString("MonitorTheHealthOfTheLocalService", resourceCulture);
            }
        }
        
        internal static string MultiplexerName {
            get {
                return ResourceManager.GetString("MultiplexerName", resourceCulture);
            }
        }
        
        internal static string MustMatchTheProxySecretKey {
            get {
                return ResourceManager.GetString("MustMatchTheProxySecretKey", resourceCulture);
            }
        }
        
        internal static string MustMatchTheVisitorsSecretKey {
            get {
                return ResourceManager.GetString("MustMatchTheVisitorsSecretKey", resourceCulture);
            }
        }
        
        internal static string NETRuntimeInfo {
            get {
                return ResourceManager.GetString("NETRuntimeInfo", resourceCulture);
            }
        }
        
        internal static string NameOfTheMultiplexer {
            get {
                return ResourceManager.GetString("NameOfTheMultiplexer", resourceCulture);
            }
        }
        
        internal static string NativeDeployment {
            get {
                return ResourceManager.GetString("NativeDeployment", resourceCulture);
            }
        }
        
        internal static string NativeDeploymentDownloadsAndExtracts {
            get {
                return ResourceManager.GetString("NativeDeploymentDownloadsAndExtracts", resourceCulture);
            }
        }
        
        internal static string NoLogsAvailable {
            get {
                return ResourceManager.GetString("NoLogsAvailable", resourceCulture);
            }
        }
        
        internal static string NoProxiesConfigured {
            get {
                return ResourceManager.GetString("NoProxiesConfigured", resourceCulture);
            }
        }
        
        internal static string NotUsed {
            get {
                return ResourceManager.GetString("NotUsed", resourceCulture);
            }
        }
        
        internal static string NoVersionsDownloaded {
            get {
                return ResourceManager.GetString("NoVersionsDownloaded", resourceCulture);
            }
        }
        
        internal static string NoVisitorsConfigured {
            get {
                return ResourceManager.GetString("NoVisitorsConfigured", resourceCulture);
            }
        }
        
        internal static string OIDC {
            get {
                return ResourceManager.GetString("OIDC", resourceCulture);
            }
        }
        
        internal static string OneHeaderPerLine {
            get {
                return ResourceManager.GetString("OneHeaderPerLine", resourceCulture);
            }
        }
        
        internal static string OpenReleasesPage {
            get {
                return ResourceManager.GetString("OpenReleasesPage", resourceCulture);
            }
        }
        
        internal static string OpenReleasesPageToolTip {
            get {
                return ResourceManager.GetString("OpenReleasesPageToolTip", resourceCulture);
            }
        }
        
        internal static string OptionalAudience {
            get {
                return ResourceManager.GetString("OptionalAudience", resourceCulture);
            }
        }
        
        internal static string OptionalLeaveEmptyToBindToAll {
            get {
                return ResourceManager.GetString("OptionalLeaveEmptyToBindToAll", resourceCulture);
            }
        }
        
        internal static string OptionalUserName {
            get {
                return ResourceManager.GetString("OptionalUserName", resourceCulture);
            }
        }
        
        internal static string OptionalUserNameToAvoidProxyNameConflicts {
            get {
                return ResourceManager.GetString("OptionalUserNameToAvoidProxyNameConflicts", resourceCulture);
            }
        }
        
        internal static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        internal static string PackageManager {
            get {
                return ResourceManager.GetString("PackageManager", resourceCulture);
            }
        }
        
        internal static string PackageManagerNotSupportFrpc {
            get {
                return ResourceManager.GetString("PackageManagerNotSupportFrpc", resourceCulture);
            }
        }
        
        internal static string PackageManagerOnlyInstallsLatest {
            get {
                return ResourceManager.GetString("PackageManagerOnlyInstallsLatest", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string PathLabel {
            get {
                return ResourceManager.GetString("PathLabel", resourceCulture);
            }
        }
        
        internal static string Platform {
            get {
                return ResourceManager.GetString("Platform", resourceCulture);
            }
        }
        
        internal static string Plugin {
            get {
                return ResourceManager.GetString("Plugin", resourceCulture);
            }
        }
        
        internal static string PluginConfiguration {
            get {
                return ResourceManager.GetString("PluginConfiguration", resourceCulture);
            }
        }
        
        internal static string PluginTypeLabel {
            get {
                return ResourceManager.GetString("PluginTypeLabel", resourceCulture);
            }
        }
        
        internal static string PortableMode {
            get {
                return ResourceManager.GetString("PortableMode", resourceCulture);
            }
        }
        
        internal static string PresetExported {
            get {
                return ResourceManager.GetString("PresetExported", resourceCulture);
            }
        }
        
        internal static string PresetImported {
            get {
                return ResourceManager.GetString("PresetImported", resourceCulture);
            }
        }
        
        internal static string PresetManagement {
            get {
                return ResourceManager.GetString("PresetManagement", resourceCulture);
            }
        }
        
        internal static string PresetName {
            get {
                return ResourceManager.GetString("PresetName", resourceCulture);
            }
        }
        
        internal static string ProcessId {
            get {
                return ResourceManager.GetString("ProcessId", resourceCulture);
            }
        }
        
        internal static string ProxiesCount {
            get {
                return ResourceManager.GetString("ProxiesCount", resourceCulture);
            }
        }
        
        internal static string ProxyConfiguration {
            get {
                return ResourceManager.GetString("ProxyConfiguration", resourceCulture);
            }
        }
        
        internal static string ProxyManagement {
            get {
                return ResourceManager.GetString("ProxyManagement", resourceCulture);
            }
        }
        
        internal static string ProxyName {
            get {
                return ResourceManager.GetString("ProxyName", resourceCulture);
            }
        }
        
        internal static string ProxyType {
            get {
                return ResourceManager.GetString("ProxyType", resourceCulture);
            }
        }
        
        internal static string QuickAccess {
            get {
                return ResourceManager.GetString("QuickAccess", resourceCulture);
            }
        }
        
        internal static string QuickShare {
            get {
                return ResourceManager.GetString("QuickShare", resourceCulture);
            }
        }
        
        internal static string RecentActivity {
            get {
                return ResourceManager.GetString("RecentActivity", resourceCulture);
            }
        }
        
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        internal static string RefreshPackageManagerList {
            get {
                return ResourceManager.GetString("RefreshPackageManagerList", resourceCulture);
            }
        }
        
        internal static string ReloadLogsFromBuffer {
            get {
                return ResourceManager.GetString("ReloadLogsFromBuffer", resourceCulture);
            }
        }
        
        internal static string RemotePort {
            get {
                return ResourceManager.GetString("RemotePort", resourceCulture);
            }
        }
        
        internal static string RemotePortLabel {
            get {
                return ResourceManager.GetString("RemotePortLabel", resourceCulture);
            }
        }
        
        internal static string RenamePreset {
            get {
                return ResourceManager.GetString("RenamePreset", resourceCulture);
            }
        }
        
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        internal static string RequiredFieldsAreMarked {
            get {
                return ResourceManager.GetString("RequiredFieldsAreMarked", resourceCulture);
            }
        }
        
        internal static string ResetToDefaults {
            get {
                return ResourceManager.GetString("ResetToDefaults", resourceCulture);
            }
        }
        
        internal static string RestartFrpc {
            get {
                return ResourceManager.GetString("RestartFrpc", resourceCulture);
            }
        }
        
        internal static string SOCKS5URL {
            get {
                return ResourceManager.GetString("SOCKS5URL", resourceCulture);
            }
        }
        
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string SaveConfiguration {
            get {
                return ResourceManager.GetString("SaveConfiguration", resourceCulture);
            }
        }
        
        internal static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        internal static string Scope {
            get {
                return ResourceManager.GetString("Scope", resourceCulture);
            }
        }
        
        internal static string SearchByName {
            get {
                return ResourceManager.GetString("SearchByName", resourceCulture);
            }
        }
        
        internal static string SearchVisitors {
            get {
                return ResourceManager.GetString("SearchVisitors", resourceCulture);
            }
        }
        
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        internal static string SecretKey {
            get {
                return ResourceManager.GetString("SecretKey", resourceCulture);
            }
        }
        
        internal static string SecureTunnelSettings {
            get {
                return ResourceManager.GetString("SecureTunnelSettings", resourceCulture);
            }
        }
        
        internal static string SecuritySettings {
            get {
                return ResourceManager.GetString("SecuritySettings", resourceCulture);
            }
        }
        
        internal static string SelectFrpcBinary {
            get {
                return ResourceManager.GetString("SelectFrpcBinary", resourceCulture);
            }
        }
        
        internal static string SelectFrpcExecutable {
            get {
                return ResourceManager.GetString("SelectFrpcExecutable", resourceCulture);
            }
        }
        
        internal static string SelectPackageManager {
            get {
                return ResourceManager.GetString("SelectPackageManager", resourceCulture);
            }
        }
        
        internal static string ServerAddress {
            get {
                return ResourceManager.GetString("ServerAddress", resourceCulture);
            }
        }
        
        internal static string ServerBindInfo {
            get {
                return ResourceManager.GetString("ServerBindInfo", resourceCulture);
            }
        }
        
        internal static string ServerConfig {
            get {
                return ResourceManager.GetString("ServerConfig", resourceCulture);
            }
        }
        
        internal static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        internal static string ServerPort {
            get {
                return ResourceManager.GetString("ServerPort", resourceCulture);
            }
        }
        
        internal static string ServiceConfiguration {
            get {
                return ResourceManager.GetString("ServiceConfiguration", resourceCulture);
            }
        }
        
        internal static string ServiceScope {
            get {
                return ResourceManager.GetString("ServiceScope", resourceCulture);
            }
        }
        
        internal static string ServiceStatus {
            get {
                return ResourceManager.GetString("ServiceStatus", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        internal static string SpecificIPToBindTo {
            get {
                return ResourceManager.GetString("SpecificIPToBindTo", resourceCulture);
            }
        }
        
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        internal static string StartContainer {
            get {
                return ResourceManager.GetString("StartContainer", resourceCulture);
            }
        }
        
        internal static string StartFrpc {
            get {
                return ResourceManager.GetString("StartFrpc", resourceCulture);
            }
        }
        
        internal static string StartOnBoot {
            get {
                return ResourceManager.GetString("StartOnBoot", resourceCulture);
            }
        }
        
        internal static string StartOnSystemBoot {
            get {
                return ResourceManager.GetString("StartOnSystemBoot", resourceCulture);
            }
        }
        
        internal static string StaticFilePluginSettings {
            get {
                return ResourceManager.GetString("StaticFilePluginSettings", resourceCulture);
            }
        }
        
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        internal static string StatusSection {
            get {
                return ResourceManager.GetString("StatusSection", resourceCulture);
            }
        }
        
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        internal static string StopContainer {
            get {
                return ResourceManager.GetString("StopContainer", resourceCulture);
            }
        }
        
        internal static string StopFrpc {
            get {
                return ResourceManager.GetString("StopFrpc", resourceCulture);
            }
        }
        
        internal static string Subdomain {
            get {
                return ResourceManager.GetString("Subdomain", resourceCulture);
            }
        }
        
        internal static string SystemDefault {
            get {
                return ResourceManager.GetString("SystemDefault", resourceCulture);
            }
        }
        
        internal static string SystemIntegration {
            get {
                return ResourceManager.GetString("SystemIntegration", resourceCulture);
            }
        }
        
        internal static string SystemLevel {
            get {
                return ResourceManager.GetString("SystemLevel", resourceCulture);
            }
        }
        
        internal static string SystemServiceSettings {
            get {
                return ResourceManager.GetString("SystemServiceSettings", resourceCulture);
            }
        }
        
        internal static string TheAddressOfTheFrpsServer {
            get {
                return ResourceManager.GetString("TheAddressOfTheFrpsServer", resourceCulture);
            }
        }
        
        internal static string TheIPOfTheLocalService {
            get {
                return ResourceManager.GetString("TheIPOfTheLocalService", resourceCulture);
            }
        }
        
        internal static string TheMultiplexerMustBeConfiguredOnTheServer {
            get {
                return ResourceManager.GetString("TheMultiplexerMustBeConfiguredOnTheServer", resourceCulture);
            }
        }
        
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        internal static string TimeoutSeconds {
            get {
                return ResourceManager.GetString("TimeoutSeconds", resourceCulture);
            }
        }
        
        internal static string Toast_BinaryLocated {
            get {
                return ResourceManager.GetString("Toast_BinaryLocated", resourceCulture);
            }
        }
        
        internal static string Toast_CannotDeleteUsedVersion {
            get {
                return ResourceManager.GetString("Toast_CannotDeleteUsedVersion", resourceCulture);
            }
        }
        
        internal static string Toast_CheckFailed {
            get {
                return ResourceManager.GetString("Toast_CheckFailed", resourceCulture);
            }
        }
        
        internal static string Toast_ConfigureFrpcFirst {
            get {
                return ResourceManager.GetString("Toast_ConfigureFrpcFirst", resourceCulture);
            }
        }
        
        internal static string Toast_ContainerStarted {
            get {
                return ResourceManager.GetString("Toast_ContainerStarted", resourceCulture);
            }
        }
        
        internal static string Toast_ContainerStopped {
            get {
                return ResourceManager.GetString("Toast_ContainerStopped", resourceCulture);
            }
        }
        
        internal static string Toast_CouldNotCheckDocker {
            get {
                return ResourceManager.GetString("Toast_CouldNotCheckDocker", resourceCulture);
            }
        }
        
        internal static string Toast_CouldNotCheckNative {
            get {
                return ResourceManager.GetString("Toast_CouldNotCheckNative", resourceCulture);
            }
        }
        
        internal static string Toast_CouldNotDeleteVersion {
            get {
                return ResourceManager.GetString("Toast_CouldNotDeleteVersion", resourceCulture);
            }
        }
        
        internal static string Toast_CouldNotDeployNative {
            get {
                return ResourceManager.GetString("Toast_CouldNotDeployNative", resourceCulture);
            }
        }
        
        internal static string Toast_CouldNotDetectFrpc {
            get {
                return ResourceManager.GetString("Toast_CouldNotDetectFrpc", resourceCulture);
            }
        }
        
        internal static string Toast_CouldNotDetermineDirectory {
            get {
                return ResourceManager.GetString("Toast_CouldNotDetermineDirectory", resourceCulture);
            }
        }
        
        internal static string Toast_CouldNotDownloadFrpc {
            get {
                return ResourceManager.GetString("Toast_CouldNotDownloadFrpc", resourceCulture);
            }
        }
        
        internal static string Toast_CouldNotGenerateDockerCompose {
            get {
                return ResourceManager.GetString("Toast_CouldNotGenerateDockerCompose", resourceCulture);
            }
        }
        
        internal static string Toast_CouldNotGetDownloadUrl {
            get {
                return ResourceManager.GetString("Toast_CouldNotGetDownloadUrl", resourceCulture);
            }
        }
        
        internal static string Toast_CouldNotGetVersion {
            get {
                return ResourceManager.GetString("Toast_CouldNotGetVersion", resourceCulture);
            }
        }
        
        internal static string Toast_CouldNotInstallFrpc {
            get {
                return ResourceManager.GetString("Toast_CouldNotInstallFrpc", resourceCulture);
            }
        }
        
        internal static string Toast_CouldNotLoadVersions {
            get {
                return ResourceManager.GetString("Toast_CouldNotLoadVersions", resourceCulture);
            }
        }
        
        internal static string Toast_CouldNotOpenConfiguration {
            get {
                return ResourceManager.GetString("Toast_CouldNotOpenConfiguration", resourceCulture);
            }
        }
        
        internal static string Toast_CouldNotOpenDownloadPage {
            get {
                return ResourceManager.GetString("Toast_CouldNotOpenDownloadPage", resourceCulture);
            }
        }
        
        internal static string Toast_CouldNotOpenUrl {
            get {
                return ResourceManager.GetString("Toast_CouldNotOpenUrl", resourceCulture);
            }
        }
        
        internal static string Toast_CouldNotSelectFile {
            get {
                return ResourceManager.GetString("Toast_CouldNotSelectFile", resourceCulture);
            }
        }
        
        internal static string Toast_CouldNotStartContainer {
            get {
                return ResourceManager.GetString("Toast_CouldNotStartContainer", resourceCulture);
            }
        }
        
        internal static string Toast_CouldNotStopContainer {
            get {
                return ResourceManager.GetString("Toast_CouldNotStopContainer", resourceCulture);
            }
        }
        
        internal static string Toast_CreateConfigFirst {
            get {
                return ResourceManager.GetString("Toast_CreateConfigFirst", resourceCulture);
            }
        }
        
        internal static string Toast_DeleteFailed {
            get {
                return ResourceManager.GetString("Toast_DeleteFailed", resourceCulture);
            }
        }
        
        internal static string Toast_DeleteFailedWithError {
            get {
                return ResourceManager.GetString("Toast_DeleteFailedWithError", resourceCulture);
            }
        }
        
        internal static string Toast_Deleted {
            get {
                return ResourceManager.GetString("Toast_Deleted", resourceCulture);
            }
        }
        
        internal static string Toast_Deploying {
            get {
                return ResourceManager.GetString("Toast_Deploying", resourceCulture);
            }
        }
        
        internal static string Toast_DeployingFrpcBinary {
            get {
                return ResourceManager.GetString("Toast_DeployingFrpcBinary", resourceCulture);
            }
        }
        
        internal static string Toast_DeploymentFailed {
            get {
                return ResourceManager.GetString("Toast_DeploymentFailed", resourceCulture);
            }
        }
        
        internal static string Toast_DockerAvailable {
            get {
                return ResourceManager.GetString("Toast_DockerAvailable", resourceCulture);
            }
        }
        
        internal static string Toast_DockerComposeSaved {
            get {
                return ResourceManager.GetString("Toast_DockerComposeSaved", resourceCulture);
            }
        }
        
        internal static string Toast_DockerContainerRunning {
            get {
                return ResourceManager.GetString("Toast_DockerContainerRunning", resourceCulture);
            }
        }
        
        internal static string Toast_DockerContainerStopped {
            get {
                return ResourceManager.GetString("Toast_DockerContainerStopped", resourceCulture);
            }
        }
        
        internal static string Toast_DockerNotAvailable {
            get {
                return ResourceManager.GetString("Toast_DockerNotAvailable", resourceCulture);
            }
        }
        
        internal static string Toast_DockerNotInstalled {
            get {
                return ResourceManager.GetString("Toast_DockerNotInstalled", resourceCulture);
            }
        }
        
        internal static string Toast_DockerReady {
            get {
                return ResourceManager.GetString("Toast_DockerReady", resourceCulture);
            }
        }
        
        internal static string Toast_Download {
            get {
                return ResourceManager.GetString("Toast_Download", resourceCulture);
            }
        }
        
        internal static string Toast_DownloadAndDeploy {
            get {
                return ResourceManager.GetString("Toast_DownloadAndDeploy", resourceCulture);
            }
        }
        
        internal static string Toast_DownloadFailed {
            get {
                return ResourceManager.GetString("Toast_DownloadFailed", resourceCulture);
            }
        }
        
        internal static string Toast_DownloadFrom {
            get {
                return ResourceManager.GetString("Toast_DownloadFrom", resourceCulture);
            }
        }
        
        internal static string Toast_Downloaded {
            get {
                return ResourceManager.GetString("Toast_Downloaded", resourceCulture);
            }
        }
        
        internal static string Toast_Downloading {
            get {
                return ResourceManager.GetString("Toast_Downloading", resourceCulture);
            }
        }
        
        internal static string Toast_DownloadingFrpc {
            get {
                return ResourceManager.GetString("Toast_DownloadingFrpc", resourceCulture);
            }
        }
        
        internal static string Toast_Error {
            get {
                return ResourceManager.GetString("Toast_Error", resourceCulture);
            }
        }
        
        internal static string Toast_FailedToStartContainer {
            get {
                return ResourceManager.GetString("Toast_FailedToStartContainer", resourceCulture);
            }
        }
        
        internal static string Toast_FailedToStopContainer {
            get {
                return ResourceManager.GetString("Toast_FailedToStopContainer", resourceCulture);
            }
        }
        
        internal static string Toast_FilePickerNotAvailable {
            get {
                return ResourceManager.GetString("Toast_FilePickerNotAvailable", resourceCulture);
            }
        }
        
        internal static string Toast_FrpcDetected {
            get {
                return ResourceManager.GetString("Toast_FrpcDetected", resourceCulture);
            }
        }
        
        internal static string Toast_FrpcDownloaded {
            get {
                return ResourceManager.GetString("Toast_FrpcDownloaded", resourceCulture);
            }
        }
        
        internal static string Toast_FrpcFound {
            get {
                return ResourceManager.GetString("Toast_FrpcFound", resourceCulture);
            }
        }
        
        internal static string Toast_FrpcFoundAt {
            get {
                return ResourceManager.GetString("Toast_FrpcFoundAt", resourceCulture);
            }
        }
        
        internal static string Toast_FrpcNotFound {
            get {
                return ResourceManager.GetString("Toast_FrpcNotFound", resourceCulture);
            }
        }
        
        internal static string Toast_FrpcNotInPath {
            get {
                return ResourceManager.GetString("Toast_FrpcNotInPath", resourceCulture);
            }
        }
        
        internal static string Toast_GenerateDockerComposeFirst {
            get {
                return ResourceManager.GetString("Toast_GenerateDockerComposeFirst", resourceCulture);
            }
        }
        
        internal static string Toast_Generated {
            get {
                return ResourceManager.GetString("Toast_Generated", resourceCulture);
            }
        }
        
        internal static string Toast_GenerationFailed {
            get {
                return ResourceManager.GetString("Toast_GenerationFailed", resourceCulture);
            }
        }
        
        internal static string Toast_InstallFailed {
            get {
                return ResourceManager.GetString("Toast_InstallFailed", resourceCulture);
            }
        }
        
        internal static string Toast_InstallFailedWithError {
            get {
                return ResourceManager.GetString("Toast_InstallFailedWithError", resourceCulture);
            }
        }
        
        internal static string Toast_Installing {
            get {
                return ResourceManager.GetString("Toast_Installing", resourceCulture);
            }
        }
        
        internal static string Toast_InstallingFrpcVia {
            get {
                return ResourceManager.GetString("Toast_InstallingFrpcVia", resourceCulture);
            }
        }
        
        internal static string Toast_InvalidBinary {
            get {
                return ResourceManager.GetString("Toast_InvalidBinary", resourceCulture);
            }
        }
        
        internal static string Toast_InvalidPath {
            get {
                return ResourceManager.GetString("Toast_InvalidPath", resourceCulture);
            }
        }
        
        internal static string Toast_NativeDeploymentNotImplemented {
            get {
                return ResourceManager.GetString("Toast_NativeDeploymentNotImplemented", resourceCulture);
            }
        }
        
        internal static string Toast_NoConfiguration {
            get {
                return ResourceManager.GetString("Toast_NoConfiguration", resourceCulture);
            }
        }
        
        internal static string Toast_NoDockerComposeFound {
            get {
                return ResourceManager.GetString("Toast_NoDockerComposeFound", resourceCulture);
            }
        }
        
        internal static string Toast_NoPath {
            get {
                return ResourceManager.GetString("Toast_NoPath", resourceCulture);
            }
        }
        
        internal static string Toast_NoSelection {
            get {
                return ResourceManager.GetString("Toast_NoSelection", resourceCulture);
            }
        }
        
        internal static string Toast_NoVersion {
            get {
                return ResourceManager.GetString("Toast_NoVersion", resourceCulture);
            }
        }
        
        internal static string Toast_NotImplemented {
            get {
                return ResourceManager.GetString("Toast_NotImplemented", resourceCulture);
            }
        }
        
        internal static string Toast_OpeningUrl {
            get {
                return ResourceManager.GetString("Toast_OpeningUrl", resourceCulture);
            }
        }
        
        internal static string Toast_PackageManagerNotAvailable {
            get {
                return ResourceManager.GetString("Toast_PackageManagerNotAvailable", resourceCulture);
            }
        }
        
        internal static string Toast_SelectFrpcPath {
            get {
                return ResourceManager.GetString("Toast_SelectFrpcPath", resourceCulture);
            }
        }
        
        internal static string Toast_SelectVersionFirst {
            get {
                return ResourceManager.GetString("Toast_SelectVersionFirst", resourceCulture);
            }
        }
        
        internal static string Toast_SelectVersionToDelete {
            get {
                return ResourceManager.GetString("Toast_SelectVersionToDelete", resourceCulture);
            }
        }
        
        internal static string Toast_ServiceManagerNotAvailable {
            get {
                return ResourceManager.GetString("Toast_ServiceManagerNotAvailable", resourceCulture);
            }
        }
        
        internal static string Toast_StartFailed {
            get {
                return ResourceManager.GetString("Toast_StartFailed", resourceCulture);
            }
        }
        
        internal static string Toast_StopFailed {
            get {
                return ResourceManager.GetString("Toast_StopFailed", resourceCulture);
            }
        }
        
        internal static string Toast_VersionDeleted {
            get {
                return ResourceManager.GetString("Toast_VersionDeleted", resourceCulture);
            }
        }
        
        internal static string Toast_VersionInUse {
            get {
                return ResourceManager.GetString("Toast_VersionInUse", resourceCulture);
            }
        }
        
        internal static string Toast_CannotDelete {
            get {
                return ResourceManager.GetString("Toast_CannotDelete", resourceCulture);
            }
        }
        
        internal static string Toast_NotManagedByApp {
            get {
                return ResourceManager.GetString("Toast_NotManagedByApp", resourceCulture);
            }
        }
        
        internal static string Toast_NotAvailable {
            get {
                return ResourceManager.GetString("Toast_NotAvailable", resourceCulture);
            }
        }
        
        internal static string Toast_NoBinary {
            get {
                return ResourceManager.GetString("Toast_NoBinary", resourceCulture);
            }
        }
        
        internal static string Toast_NoConfig {
            get {
                return ResourceManager.GetString("Toast_NoConfig", resourceCulture);
            }
        }
        
        internal static string Toast_ServiceInstalled {
            get {
                return ResourceManager.GetString("Toast_ServiceInstalled", resourceCulture);
            }
        }
        
        internal static string Toast_FrpcServiceInstalled {
            get {
                return ResourceManager.GetString("Toast_FrpcServiceInstalled", resourceCulture);
            }
        }
        
        internal static string Toast_CouldNotInstallService {
            get {
                return ResourceManager.GetString("Toast_CouldNotInstallService", resourceCulture);
            }
        }
        
        internal static string Toast_ServiceInstallFailed {
            get {
                return ResourceManager.GetString("Toast_ServiceInstallFailed", resourceCulture);
            }
        }
        
        internal static string Toast_ServiceUninstalled {
            get {
                return ResourceManager.GetString("Toast_ServiceUninstalled", resourceCulture);
            }
        }
        
        internal static string Toast_FrpcServiceUninstalled {
            get {
                return ResourceManager.GetString("Toast_FrpcServiceUninstalled", resourceCulture);
            }
        }
        
        internal static string Toast_UninstallFailed {
            get {
                return ResourceManager.GetString("Toast_UninstallFailed", resourceCulture);
            }
        }
        
        internal static string Toast_CouldNotUninstallService {
            get {
                return ResourceManager.GetString("Toast_CouldNotUninstallService", resourceCulture);
            }
        }
        
        internal static string Toast_ServiceUninstallFailed {
            get {
                return ResourceManager.GetString("Toast_ServiceUninstallFailed", resourceCulture);
            }
        }
        
        internal static string Toast_ServiceStarted {
            get {
                return ResourceManager.GetString("Toast_ServiceStarted", resourceCulture);
            }
        }
        
        internal static string Toast_FrpcServiceStarted {
            get {
                return ResourceManager.GetString("Toast_FrpcServiceStarted", resourceCulture);
            }
        }
        
        internal static string Toast_CouldNotStartService {
            get {
                return ResourceManager.GetString("Toast_CouldNotStartService", resourceCulture);
            }
        }
        
        internal static string Toast_ServiceStartFailed {
            get {
                return ResourceManager.GetString("Toast_ServiceStartFailed", resourceCulture);
            }
        }
        
        internal static string Toast_ServiceStopped {
            get {
                return ResourceManager.GetString("Toast_ServiceStopped", resourceCulture);
            }
        }
        
        internal static string Toast_FrpcServiceStopped {
            get {
                return ResourceManager.GetString("Toast_FrpcServiceStopped", resourceCulture);
            }
        }
        
        internal static string Toast_CouldNotStopService {
            get {
                return ResourceManager.GetString("Toast_CouldNotStopService", resourceCulture);
            }
        }
        
        internal static string Toast_ServiceStopFailed {
            get {
                return ResourceManager.GetString("Toast_ServiceStopFailed", resourceCulture);
            }
        }
        
        internal static string Toast_CouldNotFetchVersions {
            get {
                return ResourceManager.GetString("Toast_CouldNotFetchVersions", resourceCulture);
            }
        }
        
        internal static string Toast_Installed {
            get {
                return ResourceManager.GetString("Toast_Installed", resourceCulture);
            }
        }
        
        internal static string Toast_FrpcInstalledVia {
            get {
                return ResourceManager.GetString("Toast_FrpcInstalledVia", resourceCulture);
            }
        }
        
        internal static string Toast_BinaryNotFound {
            get {
                return ResourceManager.GetString("Toast_BinaryNotFound", resourceCulture);
            }
        }
        
        internal static string Toast_VersionSelected {
            get {
                return ResourceManager.GetString("Toast_VersionSelected", resourceCulture);
            }
        }
        
        internal static string Toast_WillUseVersion {
            get {
                return ResourceManager.GetString("Toast_WillUseVersion", resourceCulture);
            }
        }
        
        internal static string Toast_AdminRequired {
            get {
                return ResourceManager.GetString("Toast_AdminRequired", resourceCulture);
            }
        }
        
        internal static string Toast_AdminRequiredMessage {
            get {
                return ResourceManager.GetString("Toast_AdminRequiredMessage", resourceCulture);
            }
        }
        
        internal static string Toast_AdminCancelled {
            get {
                return ResourceManager.GetString("Toast_AdminCancelled", resourceCulture);
            }
        }
        
        internal static string Toast_AdminCancelledMessage {
            get {
                return ResourceManager.GetString("Toast_AdminCancelledMessage", resourceCulture);
            }
        }
        
        internal static string CannotDeleteNotManaged {
            get {
                return ResourceManager.GetString("CannotDeleteNotManaged", resourceCulture);
            }
        }
        
        internal static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        internal static string TokenEndpoint {
            get {
                return ResourceManager.GetString("TokenEndpoint", resourceCulture);
            }
        }
        
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        internal static string TransportEnabled {
            get {
                return ResourceManager.GetString("TransportEnabled", resourceCulture);
            }
        }
        
        internal static string TransportOptions {
            get {
                return ResourceManager.GetString("TransportOptions", resourceCulture);
            }
        }
        
        internal static string TransportProtocol {
            get {
                return ResourceManager.GetString("TransportProtocol", resourceCulture);
            }
        }
        
        internal static string TransportSettings {
            get {
                return ResourceManager.GetString("TransportSettings", resourceCulture);
            }
        }
        
        internal static string TypeLabel {
            get {
                return ResourceManager.GetString("TypeLabel", resourceCulture);
            }
        }
        
        internal static string UninstallService {
            get {
                return ResourceManager.GetString("UninstallService", resourceCulture);
            }
        }
        
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        internal static string UsePackageManager {
            get {
                return ResourceManager.GetString("UsePackageManager", resourceCulture);
            }
        }
        
        internal static string UserLevel {
            get {
                return ResourceManager.GetString("UserLevel", resourceCulture);
            }
        }
        
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        internal static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        internal static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
        
        internal static string VersionManagementHint {
            get {
                return ResourceManager.GetString("VersionManagementHint", resourceCulture);
            }
        }
        
        internal static string ClientId {
            get {
                return ResourceManager.GetString("ClientId", resourceCulture);
            }
        }
        
        internal static string CrtPath {
            get {
                return ResourceManager.GetString("CrtPath", resourceCulture);
            }
        }
        
        internal static string Eg {
            get {
                return ResourceManager.GetString("Eg", resourceCulture);
            }
        }
        
        internal static string EgConsolePathToLogfile {
            get {
                return ResourceManager.GetString("EgConsolePathToLogfile", resourceCulture);
            }
        }
        
        internal static string EgOpenidProfile {
            get {
                return ResourceManager.GetString("EgOpenidProfile", resourceCulture);
            }
        }
        
        internal static string EgWwwExampleCom {
            get {
                return ResourceManager.GetString("EgWwwExampleCom", resourceCulture);
            }
        }
        
        internal static string HTTPProxyUrl {
            get {
                return ResourceManager.GetString("HTTPProxyUrl", resourceCulture);
            }
        }
        
        internal static string HTTPToHttpsPluginSettings {
            get {
                return ResourceManager.GetString("HTTPToHttpsPluginSettings", resourceCulture);
            }
        }
        
        internal static string HttpsToHTTPPluginSettings {
            get {
                return ResourceManager.GetString("HttpsToHTTPPluginSettings", resourceCulture);
            }
        }
        
        internal static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        internal static string Keypath {
            get {
                return ResourceManager.GetString("Keypath", resourceCulture);
            }
        }
        
        internal static string Socks {
            get {
                return ResourceManager.GetString("Socks", resourceCulture);
            }
        }
        
        internal static string TcpMultiplexerSettings {
            get {
                return ResourceManager.GetString("TcpMultiplexerSettings", resourceCulture);
            }
        }
        
        internal static string TcpMux {
            get {
                return ResourceManager.GetString("TcpMux", resourceCulture);
            }
        }
        
        internal static string UrlPrefix {
            get {
                return ResourceManager.GetString("UrlPrefix", resourceCulture);
            }
        }
        
        internal static string WillBeRemovedAfterSaving {
            get {
                return ResourceManager.GetString("WillBeRemovedAfterSaving", resourceCulture);
            }
        }
        
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        internal static string ViewRealtimeLogsFromFrpc {
            get {
                return ResourceManager.GetString("ViewRealtimeLogsFromFrpc", resourceCulture);
            }
        }
        
        internal static string VisitorConfiguration {
            get {
                return ResourceManager.GetString("VisitorConfiguration", resourceCulture);
            }
        }
        
        internal static string VisitorManagement {
            get {
                return ResourceManager.GetString("VisitorManagement", resourceCulture);
            }
        }
        
        internal static string VisitorName {
            get {
                return ResourceManager.GetString("VisitorName", resourceCulture);
            }
        }
        
        internal static string VisitorType {
            get {
                return ResourceManager.GetString("VisitorType", resourceCulture);
            }
        }
        
        internal static string Visitors {
            get {
                return ResourceManager.GetString("Visitors", resourceCulture);
            }
        }
        
        internal static string VisitorsAllowYouToConnect {
            get {
                return ResourceManager.GetString("VisitorsAllowYouToConnect", resourceCulture);
            }
        }
    }
}
