name: "Package macOS DMG"
description: "Create macOS .dmg disk images from previously built macOS zip artifacts"

inputs:
  version:
    description: "Version string used in input zip names and output dmg names"
    required: true

  zip_dir:
    description: "Directory containing FrapaClonia-<version>-osx-*.zip files"
    required: false
    default: "."

  publish_root:
    description: "Directory containing published outputs under <publish_root>/<rid> (preferred over zips when present)"
    required: false
    default: "out"

  app_name:
    description: "App bundle name (also expected executable name inside the zip)"
    required: false
    default: "FrapaClonia"

  bundle_id:
    description: "CFBundleIdentifier"
    required: false
    default: "com.hnrobert.frapaclonia"

  icon_icns:
    description: "Path to .icns file to embed into the app bundle"
    required: false
    default: "assets/images/favicon.icns"

  plist_template:
    description: "Path to Info.plist template containing @APP_NAME@, @BUNDLE_ID@, @VERSION@ placeholders"
    required: false
    default: "assets/manifests/Info.plist.template"

  output_dir:
    description: "Where to place generated .dmg files"
    required: false
    default: "."

  rids:
    description: "Space-separated list of macOS RIDs to package"
    required: false
    default: "osx-arm64 osx-x64"

runs:
  using: "composite"
  steps:
    - name: Create DMG(s)
      shell: bash
      run: |
        set -euo pipefail

        APP_NAME="${{ inputs.app_name }}"
        VERSION="${{ inputs.version }}"
        ZIP_DIR="${{ inputs.zip_dir }}"
        PUBLISH_ROOT="${{ inputs.publish_root }}"
        ICON_SRC="${{ inputs.icon_icns }}"
        PLIST_TEMPLATE="${{ inputs.plist_template }}"
        OUT_DIR="${{ inputs.output_dir }}"
        BUNDLE_ID="${{ inputs.bundle_id }}"
        RIDS="${{ inputs.rids }}"

        if [ ! -f "$ICON_SRC" ]; then
          echo "Missing icon: $ICON_SRC" >&2
          exit 1
        fi

        if [ ! -f "$PLIST_TEMPLATE" ]; then
          echo "Missing plist template: $PLIST_TEMPLATE" >&2
          exit 1
        fi

        rm -rf work bundle
        mkdir -p work bundle "$OUT_DIR"

        for RID in $RIDS; do
          SRC_DIR=""
          if [ -d "$PUBLISH_ROOT/$RID" ]; then
            SRC_DIR="$PUBLISH_ROOT/$RID"
          else
            ZIP_PATH="$ZIP_DIR/$APP_NAME-$VERSION-$RID.zip"
            if [ ! -f "$ZIP_PATH" ]; then
              echo "Missing published dir ($PUBLISH_ROOT/$RID) and missing zip: $ZIP_PATH" >&2
              exit 1
            fi
            unzip -q "$ZIP_PATH" -d "work/$RID"
            SRC_DIR="work/$RID"
          fi

          case "$RID" in
            osx-arm64) DMG_SUFFIX="macos-arm64" ;;
            osx-x64) DMG_SUFFIX="macos-x64" ;;
            *) DMG_SUFFIX="$RID" ;;
          esac

          BUNDLE_DIR="bundle/$RID"
          APP_DIR="$BUNDLE_DIR/$APP_NAME.app"
          CONTENTS_DIR="$APP_DIR/Contents"
          MACOS_DIR="$CONTENTS_DIR/MacOS"
          RES_DIR="$CONTENTS_DIR/Resources"
          DMG_NAME="$APP_NAME-$VERSION-$DMG_SUFFIX.dmg"
          DMG_PATH="$OUT_DIR/$DMG_NAME"

          rm -rf "$BUNDLE_DIR"
          mkdir -p "$MACOS_DIR" "$RES_DIR"

          cp -R "$SRC_DIR/"* "$MACOS_DIR/"
          cp "$ICON_SRC" "$RES_DIR/AppIcon.icns"

          escape_sed_repl() {
            printf '%s' "$1" | sed -e 's/[\\/&]/\\&/g'
          }

          APP_NAME_ESC="$(escape_sed_repl "$APP_NAME")"
          BUNDLE_ID_ESC="$(escape_sed_repl "$BUNDLE_ID")"
          VERSION_ESC="$(escape_sed_repl "$VERSION")"

          sed \
            -e "s/@APP_NAME@/${APP_NAME_ESC}/g" \
            -e "s/@BUNDLE_ID@/${BUNDLE_ID_ESC}/g" \
            -e "s/@VERSION@/${VERSION_ESC}/g" \
            "$PLIST_TEMPLATE" > "$CONTENTS_DIR/Info.plist"

          # Remove debug artifacts from the shipped app bundle.
          find "$MACOS_DIR" -name '*.pdb' -type f -delete || true
          find "$MACOS_DIR" -name '*.dSYM' -type d -prune -exec rm -rf {} + || true

          # Ensure the main binary is executable.
          chmod +x "$MACOS_DIR/$APP_NAME" || true

          # Ad-hoc sign the .app to reduce macOS "is damaged" Gatekeeper failures.
          if command -v codesign >/dev/null 2>&1; then
            codesign --force --deep --sign - "$APP_DIR" || true
            codesign --verify --deep --verbose=2 "$APP_DIR" || true
          fi

          rm -f "$DMG_PATH"
          hdiutil create -volname "$APP_NAME" -srcfolder "$APP_DIR" -ov -format UDZO "$DMG_PATH"

          echo "Created: $DMG_PATH"

        done
